version: '2'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    restart: on-failure:10
    hostname: zookeeper
    container_name: zookeeper
    healthcheck:
      test: echo srvr | nc zookeeper 2181 || exit 1
      retries: 10
      interval: 20s
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./volumes/zk-data:/var/lib/zookeeper/data
      - ./volumes/zk-txn-logs:/var/lib/zookeeper/log
    networks:
      - kafka-nifi

  kafka0:
    image: confluentinc/cp-kafka:7.6.1
    hostname: kafka0
    container_name: kafka0
    restart: on-failure:10
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka0:29092,LISTENER_DOCKER_EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: 'LISTENER_DOCKER_INTERNAL'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./volumes/kafka0-data:/var/lib/kafka/data
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - kafka-nifi

  kafka1:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka1
    hostname: kafka1
    restart: on-failure:10
    ports:
      - "9091:9091"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:29091,LISTENER_DOCKER_EXTERNAL://localhost:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: 'LISTENER_DOCKER_INTERNAL'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./volumes/kafka1-data:/var/lib/kafka/data
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - kafka-nifi

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.1
    container_name: schema-registry
    hostname: schema-registry
    ports:
      - "8085:8085"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8085
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka0:29092,kafka1:29091
    depends_on:
      - kafka0
      - kafka1
    networks:
      - kafka-nifi

  nifi0:
    image: apache/nifi:1.26.0
    container_name: nifi0
    hostname: nifi0
    ports:
      - "6980:8080"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      - NIFI_SENSITIVE_PROPS_KEY=MySuperSecretKey
    depends_on:
      - zookeeper
      - kafka0
      - kafka1
      - schema-registry
    volumes:
      - ./volumes/nifi0-data:/opt/nifi/nifi-current/flowfile_repository
      - ./volumes/nifi0-data:/opt/nifi/nifi-current/content_repository
      - ./volumes/nifi0-data:/opt/nifi/nifi-current/database_repository
      - ./volumes/nifi0-data:/opt/nifi/nifi-current/provenance_repository
      - ./volumes/nifi0-data:/opt/nifi/nifi-current/state
      - ./volumes/nifi0-data:/opt/nifi/nifi-current/conf
      - ./volumes/core-site.xml:/opt/nifi/nifi-current/hadoop-conf/core-site.xml
      - ./volumes/hdfs-site.xml:/opt/nifi/nifi-current/hadoop-conf/hdfs-site.xml
    networks:
      - kafka-nifi
      - nifi-hadoop

  nifi1:
    image: apache/nifi:1.26.0
    container_name: nifi1
    hostname: nifi1
    ports:
      - "6979:8080"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      - NIFI_SENSITIVE_PROPS_KEY=MySuperSecretKey
    depends_on:
      - zookeeper
      - kafka0
      - kafka1
      - schema-registry
    volumes:
      - ./volumes/nifi1-data:/opt/nifi/nifi-current/flowfile_repository
      - ./volumes/nifi1-data:/opt/nifi/nifi-current/content_repository
      - ./volumes/nifi1-data:/opt/nifi/nifi-current/database_repository
      - ./volumes/nifi1-data:/opt/nifi/nifi-current/provenance_repository
      - ./volumes/nifi1-data:/opt/nifi/nifi-current/state
      - ./volumes/nifi1-data:/opt/nifi/nifi-current/conf
      - ./volumes/core-site.xml:/opt/nifi/nifi-current/hadoop-conf/core-site.xml
      - ./volumes/hdfs-site.xml:/opt/nifi/nifi-current/hadoop-conf/hdfs-site.xml
    networks:
      - kafka-nifi
      - nifi-hadoop
      
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: on-failure:10
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - ./hadoop-volume/hadoop_namenode:/hadoop/dfs/name
      - ./hadoop-volume/hadoop_home:/home
    environment:
      - CLUSTER_NAME=data-flow
    env_file:
      - ./hadoop.env
    networks:
      - nifi-hadoop

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    restart: on-failure:10
    volumes:
      - ./hadoop-volume/hadoop_datanode1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    networks:
      - nifi-hadoop
  
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: on-failure:10
    ports:
      - "8088:8088"
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode1:9864"
    env_file:
      - ./hadoop.env
    networks:
      - nifi-hadoop

  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    restart: on-failure:10
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode1:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    networks:
      - nifi-hadoop
  
  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    restart: on-failure:10
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode1:9864 resourcemanager:8088"
    volumes:
      - ./hadoop-volume/hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    networks:
      - nifi-hadoop
      
networks:
  kafka-nifi:
    driver: bridge
  nifi-hadoop:
    driver: bridge